### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by AtomicNess123** [kbroman/lineup#3]
I can't seem to install this package. Not available for my R version.

**Comment by kbroman** [comment]
Upgrade to a newer version of R or install from source.

**Comment by AtomicNess123** [comment]
Pardon my ignorance, how do I install a package from scratch?

**Comment by kbroman** [comment]
See <https://stackoverflow.com/questions/1474081/how-do-i-install-an-r-package-from-source>

It would be helpful to know more about your situation, such as the version of R that you are using, and your operating system. 

The lineup package includes C code and so needs compiler tools to install from source. On Windows, you need [Rtools](https://cran.r-project.org/bin/windows/Rtools/). On Mac, XCode. See <https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites>

**Comment by AtomicNess123** [comment]
Thanks, I'm on Catalina, and my RStudio version is 1.41717. I will look at those sources, thanks.

**Comment by kbroman** [comment]
More important is the version of R, which is among the things printed when you start RStudio. Or type `R.version`

**Comment by AtomicNess123** [comment]
Thank you. My version is `R version 4.1.0 (2021-05-18)`

**Comment by kbroman** [comment]
Then that’s really puzzling. I don’t see why you can’t just do

    install.packages(“lineup”)

Can you should the exact input you used and error message you received?

**Comment by AtomicNess123** [comment]
Ok.. for some reason now it worked! Apologies.
